# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_strucvol_rcpp_hello_world', PACKAGE = 'strucvol')
}

lcrec <- function(y, logsigma2, alpha0, alpha1, beta1) {
    .Call('_strucvol_lcrec', PACKAGE = 'strucvol', y, logsigma2, alpha0, alpha1, beta1)
}

derivreclm <- function(leta2, logsigma2, beta1, lm2) {
    .Call('_strucvol_derivreclm', PACKAGE = 'strucvol', leta2, logsigma2, beta1, lm2)
}

derivreclev <- function(leta2, logsigma2, beta1) {
    .Call('_strucvol_derivreclev', PACKAGE = 'strucvol', leta2, logsigma2, beta1)
}

cstoch <- function(h, eta, sbeta, sigma, mu, l) {
    .Call('_strucvol_cstoch', PACKAGE = 'strucvol', h, eta, sbeta, sigma, mu, l)
}

